services:
  web:
    build: .
    container_name: web
    tty: true
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/
